### ISSUE TITLE
CLI flags persist across projects

### ISSUE THREAD

**Issue by jeremy-coleman** [mihe/mojo#1]
![image](https://user-images.githubusercontent.com/25135855/47176474-b02dc980-d2e3-11e8-8590-7a13bbf80024.png)

I cloned and ran this repo about a month ago just out of curiosity, and I hadn't seen any issues until today when running ts-node/register with parcel-bundler in the main process.  the file is below:

```ts
import { app, BrowserWindow } from 'electron'
//import * as path from 'path'
const Bundler = require("parcel-bundler");




//createDevWindow();



let mainWindow;
let parcelStarted = false

async function createParcelWindow() {

  mainWindow = new BrowserWindow({
    width: 800,
    height: 600
  });

  mainWindow.loadURL("http://localhost:1234");

  mainWindow.on("closed", function() {
    mainWindow = null;
  });
}


const INDEX_FILE = "./src/client/index.html";

const options = {
  cache: false
};

async function createDevWindow() {
  const bundler = new Bundler(INDEX_FILE, options);
  await bundler.serve().then(async () => {
    try {
     await createParcelWindow()
     return parcelStarted = true
    }
    catch(e){
      console.log(e)
    }

})
}

app.on("ready", createDevWindow);


app.on("window-all-closed", function() {
  if (process.platform !== "darwin") {
    app.quit();
  }
});


app.on("activate", function() {
  if (parcelStarted = false) {
    createDevWindow();
  }
});

```

i am starting the electron process via npm script:
"tse": "cross-env NODE_ENV=development electron -r ts-node/register ./src/desktop/main.ts",

a few steps taken:
1)i uninstalled ts-node globally(i thought it might be some caching issue),
2)uninstalled electron globally (at least npm uninstall -g electron) there's probably several copies per version still around though. 
3) force reinstalled electron versions 3.0.4 and 4.0.0-beta.3 using npm script "force:rebuild": "npm rebuild --runtime=electron --target=4.0.0-beta.3 --disturl=https://atom.io/download/atom-shell --abi=64",
4) clean reinstall using yarn - same error
5) force reinstall using .npmrc file: save-exact = true
disturl = "https://atom.io/download/electron"
target = "3.0.4" (and 4.0.0-beta.3)
runtime "electron"
build-from-source true

**Comment by jeremy-coleman** [comment]
it only occurs when trying to run parcel bundler through the main process - using ts-node/register on a cookie cutter entry file has no issues ex:
```ts

import { app, BrowserWindow } from 'electron'
import * as path from 'path'


let mainWindow;

function createWindow() {

  mainWindow = new BrowserWindow({
    width: 800,
    height: 600
  });


  if (process.env.NODE_ENV === "development") {
    mainWindow.loadURL("http://localhost:1234");
  } else {
    mainWindow.loadURL("file:///" + path.join(__dirname, "./index.html"));
  }


  mainWindow.on("closed", function() {
    mainWindow = null;
  });
}


app.on("ready", createWindow);


app.on("window-all-closed", function() {
  if (process.platform !== "darwin") {
    app.quit();
  }
});


app.on("activate", function() {
  if (mainWindow === null) {
    createWindow();
  }
});
```

I'm curious what you think is causing mojo's settings to stick around, even after force updating and clean installing. It's obviously caused by your code, but i thought you'd be the best person to go to for initial insight

**Comment by mihe** [comment]
I'm thoroughly confused. Were you intending to post this issue to the [mojo.js](https://github.com/crcn-archive/mojo.js) repo?

**Comment by jeremy-coleman** [comment]
No, this is the only mojo related package i have ever ran

**Comment by mihe** [comment]
Then I'm even more confused.

1. What is this "security issue" you mention in the title?
1. Why are you using `parcel-bundler` on an Electron application?
1. Why are you registering `ts-node` with Electron and not just using the compiled TypeScript output?
1. What do you mean by "causing mojo's settings to stick around"?

**Comment by jeremy-coleman** [comment]
1) completely new one
2) security issue(?) is that somehow my electron's .exe is using CLI flags  i ran like a month ago (which i think is from mojo?), and taken many steps to try to reset. I am unsure if the --mojo-platform-channel-handle is related to your repo at all? ( i was thinking it could have been caused by node-hot / chokadir / something else?) all of those other flags are options you can pass to electron when you create an instance of BrowserWindow in the main process
3) by settings i just meant the cli flag being passed

I don't think this has anything to do with your mojo demo, if anything, it's a problem with electron or ts-node. It could be that the mojo flag is some internal electron flag that i've never seen before and not have anything to do with this at all, I just reached out to you because i was hoping you might have some insight.

i put up a branch to maybe reproduce the error, it may not do anything on your system though
https://github.com/jeremy-coleman/electron_parcel_tsnode/tree/issue

**Comment by mihe** [comment]
Mojo is also the name of [Chromium's IPC system](https://chromium.googlesource.com/chromium/src/+/master/mojo/README.md), so `--mojo-platform-channel` is not related to my repo. The other flags in your screenshot are just vanilla Electron/Chromium flags by the looks of it.

I don't have any idea what might have caused your issue unfortunately.
